import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-red-hat",
});

export const metadata: Metadata = {
  title: "Lux Metallic",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "var(--font-red-hat)",
  /** Optional: customize dark colors here */
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={`${redHat.className} antialiased`}>
        <MantineProvider
          theme={theme}
          defaultColorScheme="dark"
          withCssVariables
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
